using Writer.Shared.Ribbon;

namespace Writer.App.Presentation.Ribbon;

public enum WriterRibbonCommandAction
{
    About,
    AcceptThis,
    AddToDictionary,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Allcaps,
    Bibliography,
    BlankPage,
    Bold,
    Bookmark,
    BookmarkManager,
    BordersShading,
    BuildingBlocksOrganizer,
    Bullets,
    Caption,
    CcCheckbox,
    CcCombo,
    CcDate,
    CcDropdown,
    CcRichtext,
    CcText,
    CellAlignBottomCenter,
    CellAlignBottomLeft,
    CellAlignBottomRight,
    CellAlignMiddleCenter,
    CellAlignMiddleLeft,
    CellAlignMiddleRight,
    CellAlignTopCenter,
    CellAlignTopLeft,
    CellAlignTopRight,
    CellTextDirectionHorizontal,
    CellTextDirectionRotate270,
    CellTextDirectionRotate90,
    ChangeCase,
    CharBorder,
    CharShading,
    Chart,
    ChartAxisTitles,
    ChartEditData,
    ChartSize,
    ChartSizeDialog,
    ChartTitle,
    ChartToggleLegend,
    CheckAccessibility,
    CheckUpdates,
    Citation,
    CitationStyle,
    ClearFormatting,
    ColumnBreak,
    Columns,
    ColumnsLeft,
    ColumnsMore,
    ColumnsOne,
    ColumnsRight,
    ColumnsThree,
    ColumnsTwo,
    Combine,
    Compare,
    Copy,
    CopyDiagnostics,
    CoverPage,
    CrossReference,
    CustomizeColors,
    CustomizeFonts,
    CustomMargins,
    CustomParagraphSpacing,
    Cut,
    Datetime,
    DeleteComment,
    DifferentFirstPage,
    DrawTable,
    DropCap,
    DropCap_Dropped,
    DropCap_InMargin,
    DropCap_None,
    DropCapDropped,
    DropCapInMargin,
    DropCapNone,
    DropCapOptions,
    EditHyperlink,
    Endnote,
    Equation,
    Eraser,
    Feedback,
    Field,
    Find,
    FontColor,
    FontDialog,
    FontFamily,
    FontSize,
    Footer,
    Footnote,
    FootnoteEndnoteOptions,
    FormatPainter,
    FormattingMarks,
    GrowFont,
    Header,
    HelpOnline,
    HfClose,
    HfDifferentFirstPage,
    HfDifferentOddEven,
    HfEditEvenFooter,
    HfEditEvenHeader,
    HfEditFirstFooter,
    HfEditFirstHeader,
    HfEditFooter,
    HfEditHeader,
    HfFooterFromBottom,
    HfGoToFooter,
    HfGoToHeader,
    HfHeaderFromTop,
    HfInsertDatetime,
    HfInsertField,
    HfInsertPageNumber,
    HfInsertPageNumberFooter,
    Highlight,
    HorizontalRule,
    Hyperlink,
    HyperlinkTooltip,
    Hyphenation,
    HyphenationAuto,
    HyphenationManual,
    HyphenationNone,
    HyphenationOptions,
    ImageAdjustDialog,
    ImageAlignCenter,
    ImageAlignLeft,
    ImageAlignRight,
    ImageAlignToMargin,
    ImageAlignToPage,
    ImageAltText,
    ImageBevelNone,
    ImageBorder,
    ImageBrightnessMinus20,
    ImageBrightnessMinus40,
    ImageBrightnessPlus20,
    ImageBrightnessPlus40,
    ImageColorDialog,
    ImageColortempCool,
    ImageColortempNeutral,
    ImageColortempWarm,
    ImageContrastMinus20,
    ImageContrastPlus20,
    ImageCrop,
    ImageDistributeH,
    ImageDistributeV,
    ImageRecolorBlackwhite,
    ImageRecolorGrayscale,
    ImageRecolorNone,
    ImageRecolorSepia,
    ImageRecolorWashout,
    ImageReflectionNone,
    ImageReset,
    ImageSaturation0,
    ImageSaturation200,
    ImageSaturation50,
    ImageShadowNone,
    ImageSize,
    ImageTransparency25,
    ImageTransparency50,
    ImageTransparency75,
    ImageTransparencyDialog,
    IndentDecrease,
    IndentIncrease,
    IndentLeft,
    IndentRight,
    IndexInsert,
    IndexMark,
    IndexRefresh,
    InsertCaption_Equation,
    InsertCaption_Figure,
    InsertCaption_Table,
    InsertFile,
    InsertIcon,
    InspectDocument,
    Italic,
    KeepLines,
    KeepWithNext,
    LegalNotices,
    LineNumbers,
    LineNumbersContinuous,
    LineNumbersNone,
    LineNumbersOptions,
    LineNumbersRestartPage,
    LineNumbersRestartSection,
    LineSpacing,
    LinkBookmark,
    ManageSources,
    ManageStyles,
    Margins,
    MarkAsFinal,
    MarkCitation,
    MergeAddressBlock,
    MergeCheckErrors,
    MergeData,
    MergeEditRecipients,
    MergeEmail,
    MergeEnvelopes,
    MergeField,
    MergeFilterSort,
    MergeFindRecipient,
    MergeFinish,
    MergeGreetingLine,
    MergeLabels,
    MergeMatchFields,
    MergeNextRecord,
    MergePreview,
    MergePreviewFirst,
    MergePreviewLast,
    MergePreviewNext,
    MergePreviewPrevious,
    MergeRecordNumber,
    MergeRuleAsk,
    MergeRuleFillIn,
    MergeRuleIf,
    MergeRuleNextRecordIf,
    MergeRuleRef,
    MergeRules,
    MergeRuleSet,
    MergeRuleSkipRecordIf,
    MergeSequenceNumber,
    MorePaperSizes,
    MultilevelDefine,
    MultilevelDemote,
    MultilevelList,
    MultilevelPromote,
    NewComment,
    NewStyle,
    NextChange,
    NextComment,
    NextEndnote,
    NextFootnote,
    Numbering,
    Object,
    ObjectGroup,
    ObjectUngroup,
    Orientation,
    PageBreak,
    PageColor,
    PageNumber,
    PageNumberBottom,
    PageNumberCurrent,
    PageNumberFormat,
    PageNumberTop,
    PageSetup,
    PageValign,
    ParaBorder,
    ParagraphDialog,
    ParaShading,
    Paste,
    PasteMerge,
    PastePlain,
    PasteSpecial,
    Picture,
    PreviousChange,
    PreviousComment,
    PreviousEndnote,
    PreviousFootnote,
    ReadAloud,
    Redo,
    RejectThis,
    RemoveHyperlink,
    Replace,
    ReplyComment,
    ResetStyleSet,
    ResolveComment,
    RestrictEditing,
    ReviewingPane,
    SaveQuickpart,
    ScreenClipping,
    SectionBreakContinuous,
    SectionBreakEvenPage,
    SectionBreakNextPage,
    SectionBreakOddPage,
    Select,
    SetProofingLanguage,
    ShapeAlignCenter,
    ShapeAlignLeft,
    ShapeAlignRight,
    ShapeAlignToMargin,
    ShapeAlignToPage,
    ShapeAltText,
    ShapeChangeEllipse,
    ShapeChangeRectangle,
    ShapeChangeRounded,
    ShapeConvertFreeform,
    ShapeDistributeH,
    ShapeDistributeV,
    ShapeEditPoints,
    ShapeEditShape,
    ShapeEffectBevel,
    ShapeEffectGlow,
    ShapeEffectReflection,
    ShapeEffects,
    ShapeEffectShadow,
    ShapeEffectsNone,
    ShapeEffectSoftEdge,
    ShapeSize,
    ShapeStylesGallery,
    ShapeTextDirection,
    ShapeTextHorizontal,
    ShapeTextRotate270,
    ShapeTextRotate90,
    ShowComments,
    ShowMarkupBalloons,
    ShowNotes,
    ShrinkFont,
    Size,
    Smallcaps,
    Smartart,
    SmartartAddShape,
    SmartartChangeStyle,
    SmartartDemote,
    SmartartEditText,
    SmartartMoveDown,
    SmartartMoveUp,
    SmartartPromote,
    SmartartRemoveShape,
    Sort,
    SpaceAfter,
    SpaceAfterToggle,
    SpaceBefore,
    SpaceBeforeToggle,
    SpellcheckToggle,
    SplitTable,
    StartMailMerge,
    StartMailMergeDirectory,
    StartMailMergeLetters,
    StartMailMergeNormal,
    Statistics,
    Strikethrough,
    Style,
    StyleClear,
    StyleHeading1,
    StyleHeading2,
    StyleHeading3,
    StyleNormal,
    StyleSet,
    StyleTitle,
    Subscript,
    Superscript,
    Symbol,
    Table,
    TableAutofitContents,
    TableAutofitFixed,
    TableAutofitWindow,
    TableBandedCols,
    TableBandedRows,
    TableCellMargins,
    TableColWidth,
    TableDelete,
    TableDeleteCol,
    TableDeleteRow,
    TableDistributeCols,
    TableDistributeRows,
    TableFirstColumn,
    TableFormula,
    TableHeaderRow,
    TableInsertAbove,
    TableInsertBelow,
    TableInsertColLeft,
    TableInsertColRight,
    TableMergeCells,
    TableSplitCell,
    TableShading,
    TableBorders,
    TableLastColumn,
    TableLastRow,
    TableOfAuthorities,
    TableOfAuthoritiesRefresh,
    TableProperties,
    TableRepeatHeader,
    TableRowHeight,
    TableSelectCell,
    TableSelectCol,
    TableSelectRow,
    TableSelectTable,
    TableToText,
    TableViewGridlines,
    TabsDialog,
    TextToTable,
    Theme,
    ThemeColors,
    ThemeEffects,
    ThemeFonts,
    Thesaurus,
    Toc,
    TocRefresh,
    Tof,
    Tof_Equation,
    Tof_Figure,
    Tof_Table,
    TofRefresh,
    TofRefresh_Equation,
    TofRefresh_Figure,
    TofRefresh_Table,
    ToggleFieldCodes,
    Underline,
    Undo,
    UpdateFields,
    Watermark,
    WidowControl,
    Wordart,
    TestCrashReporting,
}

public sealed record WriterRibbonCommandRoute(
    string CommandId,
    WriterRibbonCommandAction Action);

/// <summary>
/// Owns the portable mapping from Writer ribbon ids to application actions. Renderers bind each
/// action to native editor, dialog, clipboard, file, focus, or window callbacks.
/// </summary>
public static class WriterRibbonCommandWorkflow
{
    private static readonly WriterRibbonCommandRoute[] RouteData =
    [
        new("writer.about", WriterRibbonCommandAction.About),
        new("writer.accept-this", WriterRibbonCommandAction.AcceptThis),
        new("writer.add-to-dictionary", WriterRibbonCommandAction.AddToDictionary),
        new("writer.align-center", WriterRibbonCommandAction.AlignCenter),
        new("writer.align-justify", WriterRibbonCommandAction.AlignJustify),
        new("writer.align-left", WriterRibbonCommandAction.AlignLeft),
        new("writer.align-right", WriterRibbonCommandAction.AlignRight),
        new("writer.allcaps", WriterRibbonCommandAction.Allcaps),
        new("writer.bibliography", WriterRibbonCommandAction.Bibliography),
        new("writer.blank-page", WriterRibbonCommandAction.BlankPage),
        new("writer.bold", WriterRibbonCommandAction.Bold),
        new("writer.bookmark", WriterRibbonCommandAction.Bookmark),
        new("writer.bookmark-manager", WriterRibbonCommandAction.BookmarkManager),
        new("writer.borders-shading", WriterRibbonCommandAction.BordersShading),
        new("writer.building-blocks-organizer", WriterRibbonCommandAction.BuildingBlocksOrganizer),
        new("writer.bullets", WriterRibbonCommandAction.Bullets),
        new("writer.caption", WriterRibbonCommandAction.Caption),
        new("writer.cc-checkbox", WriterRibbonCommandAction.CcCheckbox),
        new("writer.cc-combo", WriterRibbonCommandAction.CcCombo),
        new("writer.cc-date", WriterRibbonCommandAction.CcDate),
        new("writer.cc-dropdown", WriterRibbonCommandAction.CcDropdown),
        new("writer.cc-richtext", WriterRibbonCommandAction.CcRichtext),
        new("writer.cc-text", WriterRibbonCommandAction.CcText),
        new("writer.cell-align-bottom-center", WriterRibbonCommandAction.CellAlignBottomCenter),
        new("writer.cell-align-bottom-left", WriterRibbonCommandAction.CellAlignBottomLeft),
        new("writer.cell-align-bottom-right", WriterRibbonCommandAction.CellAlignBottomRight),
        new("writer.cell-align-middle-center", WriterRibbonCommandAction.CellAlignMiddleCenter),
        new("writer.cell-align-middle-left", WriterRibbonCommandAction.CellAlignMiddleLeft),
        new("writer.cell-align-middle-right", WriterRibbonCommandAction.CellAlignMiddleRight),
        new("writer.cell-align-top-center", WriterRibbonCommandAction.CellAlignTopCenter),
        new("writer.cell-align-top-left", WriterRibbonCommandAction.CellAlignTopLeft),
        new("writer.cell-align-top-right", WriterRibbonCommandAction.CellAlignTopRight),
        new("writer.cell-text-direction-horizontal", WriterRibbonCommandAction.CellTextDirectionHorizontal),
        new("writer.cell-text-direction-rotate270", WriterRibbonCommandAction.CellTextDirectionRotate270),
        new("writer.cell-text-direction-rotate90", WriterRibbonCommandAction.CellTextDirectionRotate90),
        new("writer.change-case", WriterRibbonCommandAction.ChangeCase),
        new("writer.char-border", WriterRibbonCommandAction.CharBorder),
        new("writer.char-shading", WriterRibbonCommandAction.CharShading),
        new("writer.chart", WriterRibbonCommandAction.Chart),
        new("writer.chart-axis-titles", WriterRibbonCommandAction.ChartAxisTitles),
        new("writer.chart-edit-data", WriterRibbonCommandAction.ChartEditData),
        new("writer.chart-size", WriterRibbonCommandAction.ChartSize),
        new("writer.chart-size-dialog", WriterRibbonCommandAction.ChartSizeDialog),
        new("writer.chart-title", WriterRibbonCommandAction.ChartTitle),
        new("writer.chart-toggle-legend", WriterRibbonCommandAction.ChartToggleLegend),
        new("writer.check-accessibility", WriterRibbonCommandAction.CheckAccessibility),
        new("writer.check-updates", WriterRibbonCommandAction.CheckUpdates),
        new("writer.citation", WriterRibbonCommandAction.Citation),
        new("writer.citation-style", WriterRibbonCommandAction.CitationStyle),
        new("writer.clear-formatting", WriterRibbonCommandAction.ClearFormatting),
        new("writer.column-break", WriterRibbonCommandAction.ColumnBreak),
        new("writer.columns", WriterRibbonCommandAction.Columns),
        new("writer.columns-left", WriterRibbonCommandAction.ColumnsLeft),
        new("writer.columns-more", WriterRibbonCommandAction.ColumnsMore),
        new("writer.columns-one", WriterRibbonCommandAction.ColumnsOne),
        new("writer.columns-right", WriterRibbonCommandAction.ColumnsRight),
        new("writer.columns-three", WriterRibbonCommandAction.ColumnsThree),
        new("writer.columns-two", WriterRibbonCommandAction.ColumnsTwo),
        new("writer.combine", WriterRibbonCommandAction.Combine),
        new("writer.compare", WriterRibbonCommandAction.Compare),
        new("writer.copy", WriterRibbonCommandAction.Copy),
        new("writer.copy-diagnostics", WriterRibbonCommandAction.CopyDiagnostics),
        new("writer.test-crash-reporting", WriterRibbonCommandAction.TestCrashReporting),
        new("writer.cover-page", WriterRibbonCommandAction.CoverPage),
        new("writer.cross-reference", WriterRibbonCommandAction.CrossReference),
        new("writer.customize-colors", WriterRibbonCommandAction.CustomizeColors),
        new("writer.customize-fonts", WriterRibbonCommandAction.CustomizeFonts),
        new("writer.custom-margins", WriterRibbonCommandAction.CustomMargins),
        new("writer.custom-paragraph-spacing", WriterRibbonCommandAction.CustomParagraphSpacing),
        new("writer.cut", WriterRibbonCommandAction.Cut),
        new("writer.datetime", WriterRibbonCommandAction.Datetime),
        new("writer.delete-comment", WriterRibbonCommandAction.DeleteComment),
        new("writer.different-first-page", WriterRibbonCommandAction.DifferentFirstPage),
        new("writer.draw-table", WriterRibbonCommandAction.DrawTable),
        new("writer.drop-cap", WriterRibbonCommandAction.DropCap),
        new("writer.drop-cap.dropped", WriterRibbonCommandAction.DropCap_Dropped),
        new("writer.drop-cap.in-margin", WriterRibbonCommandAction.DropCap_InMargin),
        new("writer.drop-cap.none", WriterRibbonCommandAction.DropCap_None),
        new("writer.drop-cap-dropped", WriterRibbonCommandAction.DropCapDropped),
        new("writer.drop-cap-in-margin", WriterRibbonCommandAction.DropCapInMargin),
        new("writer.drop-cap-none", WriterRibbonCommandAction.DropCapNone),
        new("writer.drop-cap-options", WriterRibbonCommandAction.DropCapOptions),
        new("writer.edit-hyperlink", WriterRibbonCommandAction.EditHyperlink),
        new("writer.endnote", WriterRibbonCommandAction.Endnote),
        new("writer.equation", WriterRibbonCommandAction.Equation),
        new("writer.eraser", WriterRibbonCommandAction.Eraser),
        new("writer.feedback", WriterRibbonCommandAction.Feedback),
        new("writer.field", WriterRibbonCommandAction.Field),
        new("writer.find", WriterRibbonCommandAction.Find),
        new("writer.font-color", WriterRibbonCommandAction.FontColor),
        new("writer.font-dialog", WriterRibbonCommandAction.FontDialog),
        new("writer.font-family", WriterRibbonCommandAction.FontFamily),
        new("writer.font-size", WriterRibbonCommandAction.FontSize),
        new("writer.footer", WriterRibbonCommandAction.Footer),
        new("writer.footnote", WriterRibbonCommandAction.Footnote),
        new("writer.footnote-endnote-options", WriterRibbonCommandAction.FootnoteEndnoteOptions),
        new("writer.format-painter", WriterRibbonCommandAction.FormatPainter),
        new("writer.formatting-marks", WriterRibbonCommandAction.FormattingMarks),
        new("writer.grow-font", WriterRibbonCommandAction.GrowFont),
        new("writer.header", WriterRibbonCommandAction.Header),
        new("writer.help-online", WriterRibbonCommandAction.HelpOnline),
        new("writer.hf-close", WriterRibbonCommandAction.HfClose),
        new("writer.hf-different-first-page", WriterRibbonCommandAction.HfDifferentFirstPage),
        new("writer.hf-different-odd-even", WriterRibbonCommandAction.HfDifferentOddEven),
        new("writer.hf-edit-even-footer", WriterRibbonCommandAction.HfEditEvenFooter),
        new("writer.hf-edit-even-header", WriterRibbonCommandAction.HfEditEvenHeader),
        new("writer.hf-edit-first-footer", WriterRibbonCommandAction.HfEditFirstFooter),
        new("writer.hf-edit-first-header", WriterRibbonCommandAction.HfEditFirstHeader),
        new("writer.hf-edit-footer", WriterRibbonCommandAction.HfEditFooter),
        new("writer.hf-edit-header", WriterRibbonCommandAction.HfEditHeader),
        new("writer.hf-footer-from-bottom", WriterRibbonCommandAction.HfFooterFromBottom),
        new("writer.hf-go-to-footer", WriterRibbonCommandAction.HfGoToFooter),
        new("writer.hf-go-to-header", WriterRibbonCommandAction.HfGoToHeader),
        new("writer.hf-header-from-top", WriterRibbonCommandAction.HfHeaderFromTop),
        new("writer.hf-insert-datetime", WriterRibbonCommandAction.HfInsertDatetime),
        new("writer.hf-insert-field", WriterRibbonCommandAction.HfInsertField),
        new("writer.hf-insert-page-number", WriterRibbonCommandAction.HfInsertPageNumber),
        new("writer.hf-insert-page-number-footer", WriterRibbonCommandAction.HfInsertPageNumberFooter),
        new("writer.highlight", WriterRibbonCommandAction.Highlight),
        new("writer.horizontal-rule", WriterRibbonCommandAction.HorizontalRule),
        new("writer.hyperlink", WriterRibbonCommandAction.Hyperlink),
        new("writer.hyperlink-tooltip", WriterRibbonCommandAction.HyperlinkTooltip),
        new("writer.hyphenation", WriterRibbonCommandAction.Hyphenation),
        new("writer.hyphenation-auto", WriterRibbonCommandAction.HyphenationAuto),
        new("writer.hyphenation-manual", WriterRibbonCommandAction.HyphenationManual),
        new("writer.hyphenation-none", WriterRibbonCommandAction.HyphenationNone),
        new("writer.hyphenation-options", WriterRibbonCommandAction.HyphenationOptions),
        new("writer.image-adjust-dialog", WriterRibbonCommandAction.ImageAdjustDialog),
        new("writer.image-align-center", WriterRibbonCommandAction.ImageAlignCenter),
        new("writer.image-align-left", WriterRibbonCommandAction.ImageAlignLeft),
        new("writer.image-align-right", WriterRibbonCommandAction.ImageAlignRight),
        new("writer.image-align-to-margin", WriterRibbonCommandAction.ImageAlignToMargin),
        new("writer.image-align-to-page", WriterRibbonCommandAction.ImageAlignToPage),
        new("writer.image-alt-text", WriterRibbonCommandAction.ImageAltText),
        new("writer.image-bevel-none", WriterRibbonCommandAction.ImageBevelNone),
        new("writer.image-border", WriterRibbonCommandAction.ImageBorder),
        new("writer.image-brightness-minus20", WriterRibbonCommandAction.ImageBrightnessMinus20),
        new("writer.image-brightness-minus40", WriterRibbonCommandAction.ImageBrightnessMinus40),
        new("writer.image-brightness-plus20", WriterRibbonCommandAction.ImageBrightnessPlus20),
        new("writer.image-brightness-plus40", WriterRibbonCommandAction.ImageBrightnessPlus40),
        new("writer.image-color-dialog", WriterRibbonCommandAction.ImageColorDialog),
        new("writer.image-colortemp-cool", WriterRibbonCommandAction.ImageColortempCool),
        new("writer.image-colortemp-neutral", WriterRibbonCommandAction.ImageColortempNeutral),
        new("writer.image-colortemp-warm", WriterRibbonCommandAction.ImageColortempWarm),
        new("writer.image-contrast-minus20", WriterRibbonCommandAction.ImageContrastMinus20),
        new("writer.image-contrast-plus20", WriterRibbonCommandAction.ImageContrastPlus20),
        new("writer.image-crop", WriterRibbonCommandAction.ImageCrop),
        new("writer.image-distribute-h", WriterRibbonCommandAction.ImageDistributeH),
        new("writer.image-distribute-v", WriterRibbonCommandAction.ImageDistributeV),
        new("writer.image-recolor-blackwhite", WriterRibbonCommandAction.ImageRecolorBlackwhite),
        new("writer.image-recolor-grayscale", WriterRibbonCommandAction.ImageRecolorGrayscale),
        new("writer.image-recolor-none", WriterRibbonCommandAction.ImageRecolorNone),
        new("writer.image-recolor-sepia", WriterRibbonCommandAction.ImageRecolorSepia),
        new("writer.image-recolor-washout", WriterRibbonCommandAction.ImageRecolorWashout),
        new("writer.image-reflection-none", WriterRibbonCommandAction.ImageReflectionNone),
        new("writer.image-reset", WriterRibbonCommandAction.ImageReset),
        new("writer.image-saturation-0", WriterRibbonCommandAction.ImageSaturation0),
        new("writer.image-saturation-200", WriterRibbonCommandAction.ImageSaturation200),
        new("writer.image-saturation-50", WriterRibbonCommandAction.ImageSaturation50),
        new("writer.image-shadow-none", WriterRibbonCommandAction.ImageShadowNone),
        new("writer.image-size", WriterRibbonCommandAction.ImageSize),
        new("writer.image-transparency-25", WriterRibbonCommandAction.ImageTransparency25),
        new("writer.image-transparency-50", WriterRibbonCommandAction.ImageTransparency50),
        new("writer.image-transparency-75", WriterRibbonCommandAction.ImageTransparency75),
        new("writer.image-transparency-dialog", WriterRibbonCommandAction.ImageTransparencyDialog),
        new("writer.indent-decrease", WriterRibbonCommandAction.IndentDecrease),
        new("writer.indent-increase", WriterRibbonCommandAction.IndentIncrease),
        new("writer.indent-left", WriterRibbonCommandAction.IndentLeft),
        new("writer.indent-right", WriterRibbonCommandAction.IndentRight),
        new("writer.index-insert", WriterRibbonCommandAction.IndexInsert),
        new("writer.index-mark", WriterRibbonCommandAction.IndexMark),
        new("writer.index-refresh", WriterRibbonCommandAction.IndexRefresh),
        new("writer.insert-caption.equation", WriterRibbonCommandAction.InsertCaption_Equation),
        new("writer.insert-caption.figure", WriterRibbonCommandAction.InsertCaption_Figure),
        new("writer.insert-caption.table", WriterRibbonCommandAction.InsertCaption_Table),
        new("writer.insert-file", WriterRibbonCommandAction.InsertFile),
        new("writer.insert-icon", WriterRibbonCommandAction.InsertIcon),
        new("writer.inspect-document", WriterRibbonCommandAction.InspectDocument),
        new("writer.italic", WriterRibbonCommandAction.Italic),
        new("writer.keep-lines", WriterRibbonCommandAction.KeepLines),
        new("writer.keep-with-next", WriterRibbonCommandAction.KeepWithNext),
        new("writer.legal-notices", WriterRibbonCommandAction.LegalNotices),
        new("writer.line-numbers", WriterRibbonCommandAction.LineNumbers),
        new("writer.line-numbers-continuous", WriterRibbonCommandAction.LineNumbersContinuous),
        new("writer.line-numbers-none", WriterRibbonCommandAction.LineNumbersNone),
        new("writer.line-numbers-options", WriterRibbonCommandAction.LineNumbersOptions),
        new("writer.line-numbers-restart-page", WriterRibbonCommandAction.LineNumbersRestartPage),
        new("writer.line-numbers-restart-section", WriterRibbonCommandAction.LineNumbersRestartSection),
        new("writer.line-spacing", WriterRibbonCommandAction.LineSpacing),
        new("writer.link-bookmark", WriterRibbonCommandAction.LinkBookmark),
        new("writer.manage-sources", WriterRibbonCommandAction.ManageSources),
        new("writer.manage-styles", WriterRibbonCommandAction.ManageStyles),
        new("writer.margins", WriterRibbonCommandAction.Margins),
        new("writer.mark-as-final", WriterRibbonCommandAction.MarkAsFinal),
        new("writer.mark-citation", WriterRibbonCommandAction.MarkCitation),
        new("writer.merge-address-block", WriterRibbonCommandAction.MergeAddressBlock),
        new("writer.merge-check-errors", WriterRibbonCommandAction.MergeCheckErrors),
        new("writer.merge-data", WriterRibbonCommandAction.MergeData),
        new("writer.merge-edit-recipients", WriterRibbonCommandAction.MergeEditRecipients),
        new("writer.merge-email", WriterRibbonCommandAction.MergeEmail),
        new("writer.merge-envelopes", WriterRibbonCommandAction.MergeEnvelopes),
        new("writer.merge-field", WriterRibbonCommandAction.MergeField),
        new("writer.merge-filter-sort", WriterRibbonCommandAction.MergeFilterSort),
        new("writer.merge-find-recipient", WriterRibbonCommandAction.MergeFindRecipient),
        new("writer.merge-finish", WriterRibbonCommandAction.MergeFinish),
        new("writer.merge-greeting-line", WriterRibbonCommandAction.MergeGreetingLine),
        new("writer.merge-labels", WriterRibbonCommandAction.MergeLabels),
        new("writer.merge-match-fields", WriterRibbonCommandAction.MergeMatchFields),
        new("writer.merge-next-record", WriterRibbonCommandAction.MergeNextRecord),
        new("writer.merge-preview", WriterRibbonCommandAction.MergePreview),
        new("writer.merge-preview-first", WriterRibbonCommandAction.MergePreviewFirst),
        new("writer.merge-preview-last", WriterRibbonCommandAction.MergePreviewLast),
        new("writer.merge-preview-next", WriterRibbonCommandAction.MergePreviewNext),
        new("writer.merge-preview-previous", WriterRibbonCommandAction.MergePreviewPrevious),
        new("writer.merge-record-number", WriterRibbonCommandAction.MergeRecordNumber),
        new("writer.merge-rule-ask", WriterRibbonCommandAction.MergeRuleAsk),
        new("writer.merge-rule-fill-in", WriterRibbonCommandAction.MergeRuleFillIn),
        new("writer.merge-rule-if", WriterRibbonCommandAction.MergeRuleIf),
        new("writer.merge-rule-next-record-if", WriterRibbonCommandAction.MergeRuleNextRecordIf),
        new("writer.merge-rule-ref", WriterRibbonCommandAction.MergeRuleRef),
        new("writer.merge-rules", WriterRibbonCommandAction.MergeRules),
        new("writer.merge-rule-set", WriterRibbonCommandAction.MergeRuleSet),
        new("writer.merge-rule-skip-record-if", WriterRibbonCommandAction.MergeRuleSkipRecordIf),
        new("writer.merge-sequence-number", WriterRibbonCommandAction.MergeSequenceNumber),
        new("writer.more-paper-sizes", WriterRibbonCommandAction.MorePaperSizes),
        new("writer.multilevel-define", WriterRibbonCommandAction.MultilevelDefine),
        new("writer.multilevel-demote", WriterRibbonCommandAction.MultilevelDemote),
        new("writer.multilevel-list", WriterRibbonCommandAction.MultilevelList),
        new("writer.multilevel-promote", WriterRibbonCommandAction.MultilevelPromote),
        new("writer.new-comment", WriterRibbonCommandAction.NewComment),
        new("writer.new-style", WriterRibbonCommandAction.NewStyle),
        new("writer.next-change", WriterRibbonCommandAction.NextChange),
        new("writer.next-comment", WriterRibbonCommandAction.NextComment),
        new("writer.next-endnote", WriterRibbonCommandAction.NextEndnote),
        new("writer.next-footnote", WriterRibbonCommandAction.NextFootnote),
        new("writer.numbering", WriterRibbonCommandAction.Numbering),
        new("writer.object", WriterRibbonCommandAction.Object),
        new("writer.object-group", WriterRibbonCommandAction.ObjectGroup),
        new("writer.object-ungroup", WriterRibbonCommandAction.ObjectUngroup),
        new("writer.orientation", WriterRibbonCommandAction.Orientation),
        new("writer.page-break", WriterRibbonCommandAction.PageBreak),
        new("writer.page-color", WriterRibbonCommandAction.PageColor),
        new("writer.page-number", WriterRibbonCommandAction.PageNumber),
        new("writer.page-number-bottom", WriterRibbonCommandAction.PageNumberBottom),
        new("writer.page-number-current", WriterRibbonCommandAction.PageNumberCurrent),
        new("writer.page-number-format", WriterRibbonCommandAction.PageNumberFormat),
        new("writer.page-number-top", WriterRibbonCommandAction.PageNumberTop),
        new("writer.page-setup", WriterRibbonCommandAction.PageSetup),
        new("writer.page-valign", WriterRibbonCommandAction.PageValign),
        new("writer.para-border", WriterRibbonCommandAction.ParaBorder),
        new("writer.paragraph-dialog", WriterRibbonCommandAction.ParagraphDialog),
        new("writer.para-shading", WriterRibbonCommandAction.ParaShading),
        new("writer.paste", WriterRibbonCommandAction.Paste),
        new("writer.paste-merge", WriterRibbonCommandAction.PasteMerge),
        new("writer.paste-plain", WriterRibbonCommandAction.PastePlain),
        new("writer.paste-special", WriterRibbonCommandAction.PasteSpecial),
        new("writer.picture", WriterRibbonCommandAction.Picture),
        new("writer.previous-change", WriterRibbonCommandAction.PreviousChange),
        new("writer.previous-comment", WriterRibbonCommandAction.PreviousComment),
        new("writer.previous-endnote", WriterRibbonCommandAction.PreviousEndnote),
        new("writer.previous-footnote", WriterRibbonCommandAction.PreviousFootnote),
        new("writer.read-aloud", WriterRibbonCommandAction.ReadAloud),
        new("writer.redo", WriterRibbonCommandAction.Redo),
        new("writer.reject-this", WriterRibbonCommandAction.RejectThis),
        new("writer.remove-hyperlink", WriterRibbonCommandAction.RemoveHyperlink),
        new("writer.replace", WriterRibbonCommandAction.Replace),
        new("writer.reply-comment", WriterRibbonCommandAction.ReplyComment),
        new("writer.reset-style-set", WriterRibbonCommandAction.ResetStyleSet),
        new("writer.resolve-comment", WriterRibbonCommandAction.ResolveComment),
        new("writer.restrict-editing", WriterRibbonCommandAction.RestrictEditing),
        new("writer.reviewing-pane", WriterRibbonCommandAction.ReviewingPane),
        new("writer.save-quickpart", WriterRibbonCommandAction.SaveQuickpart),
        new("writer.screen-clipping", WriterRibbonCommandAction.ScreenClipping),
        new("writer.section-break-continuous", WriterRibbonCommandAction.SectionBreakContinuous),
        new("writer.section-break-even-page", WriterRibbonCommandAction.SectionBreakEvenPage),
        new("writer.section-break-next-page", WriterRibbonCommandAction.SectionBreakNextPage),
        new("writer.section-break-odd-page", WriterRibbonCommandAction.SectionBreakOddPage),
        new("writer.select", WriterRibbonCommandAction.Select),
        new("writer.set-proofing-language", WriterRibbonCommandAction.SetProofingLanguage),
        new("writer.shape-align-center", WriterRibbonCommandAction.ShapeAlignCenter),
        new("writer.shape-align-left", WriterRibbonCommandAction.ShapeAlignLeft),
        new("writer.shape-align-right", WriterRibbonCommandAction.ShapeAlignRight),
        new("writer.shape-align-to-margin", WriterRibbonCommandAction.ShapeAlignToMargin),
        new("writer.shape-align-to-page", WriterRibbonCommandAction.ShapeAlignToPage),
        new("writer.shape-alt-text", WriterRibbonCommandAction.ShapeAltText),
        new("writer.shape-change-ellipse", WriterRibbonCommandAction.ShapeChangeEllipse),
        new("writer.shape-change-rectangle", WriterRibbonCommandAction.ShapeChangeRectangle),
        new("writer.shape-change-rounded", WriterRibbonCommandAction.ShapeChangeRounded),
        new("writer.shape-convert-freeform", WriterRibbonCommandAction.ShapeConvertFreeform),
        new("writer.shape-distribute-h", WriterRibbonCommandAction.ShapeDistributeH),
        new("writer.shape-distribute-v", WriterRibbonCommandAction.ShapeDistributeV),
        new("writer.shape-edit-points", WriterRibbonCommandAction.ShapeEditPoints),
        new("writer.shape-edit-shape", WriterRibbonCommandAction.ShapeEditShape),
        new("writer.shape-effect-bevel", WriterRibbonCommandAction.ShapeEffectBevel),
        new("writer.shape-effect-glow", WriterRibbonCommandAction.ShapeEffectGlow),
        new("writer.shape-effect-reflection", WriterRibbonCommandAction.ShapeEffectReflection),
        new("writer.shape-effects", WriterRibbonCommandAction.ShapeEffects),
        new("writer.shape-effect-shadow", WriterRibbonCommandAction.ShapeEffectShadow),
        new("writer.shape-effects-none", WriterRibbonCommandAction.ShapeEffectsNone),
        new("writer.shape-effect-soft-edge", WriterRibbonCommandAction.ShapeEffectSoftEdge),
        new("writer.shape-size", WriterRibbonCommandAction.ShapeSize),
        new("writer.shape-styles-gallery", WriterRibbonCommandAction.ShapeStylesGallery),
        new("writer.shape-text-direction", WriterRibbonCommandAction.ShapeTextDirection),
        new("writer.shape-text-horizontal", WriterRibbonCommandAction.ShapeTextHorizontal),
        new("writer.shape-text-rotate270", WriterRibbonCommandAction.ShapeTextRotate270),
        new("writer.shape-text-rotate90", WriterRibbonCommandAction.ShapeTextRotate90),
        new("writer.show-comments", WriterRibbonCommandAction.ShowComments),
        new("writer.show-markup-balloons", WriterRibbonCommandAction.ShowMarkupBalloons),
        new("writer.show-notes", WriterRibbonCommandAction.ShowNotes),
        new("writer.shrink-font", WriterRibbonCommandAction.ShrinkFont),
        new("writer.size", WriterRibbonCommandAction.Size),
        new("writer.smallcaps", WriterRibbonCommandAction.Smallcaps),
        new("writer.smartart", WriterRibbonCommandAction.Smartart),
        new("writer.smartart-add-shape", WriterRibbonCommandAction.SmartartAddShape),
        new("writer.smartart-change-style", WriterRibbonCommandAction.SmartartChangeStyle),
        new("writer.smartart-demote", WriterRibbonCommandAction.SmartartDemote),
        new("writer.smartart-edit-text", WriterRibbonCommandAction.SmartartEditText),
        new("writer.smartart-move-down", WriterRibbonCommandAction.SmartartMoveDown),
        new("writer.smartart-move-up", WriterRibbonCommandAction.SmartartMoveUp),
        new("writer.smartart-promote", WriterRibbonCommandAction.SmartartPromote),
        new("writer.smartart-remove-shape", WriterRibbonCommandAction.SmartartRemoveShape),
        new("writer.sort", WriterRibbonCommandAction.Sort),
        new("writer.space-after", WriterRibbonCommandAction.SpaceAfter),
        new("writer.space-after-toggle", WriterRibbonCommandAction.SpaceAfterToggle),
        new("writer.space-before", WriterRibbonCommandAction.SpaceBefore),
        new("writer.space-before-toggle", WriterRibbonCommandAction.SpaceBeforeToggle),
        new("writer.spellcheck-toggle", WriterRibbonCommandAction.SpellcheckToggle),
        new("writer.split-table", WriterRibbonCommandAction.SplitTable),
        new("writer.start-mail-merge", WriterRibbonCommandAction.StartMailMerge),
        new("writer.start-mail-merge-directory", WriterRibbonCommandAction.StartMailMergeDirectory),
        new("writer.start-mail-merge-letters", WriterRibbonCommandAction.StartMailMergeLetters),
        new("writer.start-mail-merge-normal", WriterRibbonCommandAction.StartMailMergeNormal),
        new("writer.statistics", WriterRibbonCommandAction.Statistics),
        new("writer.strikethrough", WriterRibbonCommandAction.Strikethrough),
        new("writer.style", WriterRibbonCommandAction.Style),
        new("writer.style-clear", WriterRibbonCommandAction.StyleClear),
        new("writer.style-heading1", WriterRibbonCommandAction.StyleHeading1),
        new("writer.style-heading2", WriterRibbonCommandAction.StyleHeading2),
        new("writer.style-heading3", WriterRibbonCommandAction.StyleHeading3),
        new("writer.style-normal", WriterRibbonCommandAction.StyleNormal),
        new("writer.style-set", WriterRibbonCommandAction.StyleSet),
        new("writer.style-title", WriterRibbonCommandAction.StyleTitle),
        new("writer.subscript", WriterRibbonCommandAction.Subscript),
        new("writer.superscript", WriterRibbonCommandAction.Superscript),
        new("writer.symbol", WriterRibbonCommandAction.Symbol),
        new("writer.table", WriterRibbonCommandAction.Table),
        new("writer.table-autofit-contents", WriterRibbonCommandAction.TableAutofitContents),
        new("writer.table-autofit-fixed", WriterRibbonCommandAction.TableAutofitFixed),
        new("writer.table-autofit-window", WriterRibbonCommandAction.TableAutofitWindow),
        new("writer.table-banded-cols", WriterRibbonCommandAction.TableBandedCols),
        new("writer.table-banded-rows", WriterRibbonCommandAction.TableBandedRows),
        new("writer.table-cell-margins", WriterRibbonCommandAction.TableCellMargins),
        new("writer.table-col-width", WriterRibbonCommandAction.TableColWidth),
        new("writer.table-delete", WriterRibbonCommandAction.TableDelete),
        new("writer.table-delete-col", WriterRibbonCommandAction.TableDeleteCol),
        new("writer.table-delete-row", WriterRibbonCommandAction.TableDeleteRow),
        new("writer.table-distribute-cols", WriterRibbonCommandAction.TableDistributeCols),
        new("writer.table-distribute-rows", WriterRibbonCommandAction.TableDistributeRows),
        new("writer.table-first-column", WriterRibbonCommandAction.TableFirstColumn),
        new("writer.table-formula", WriterRibbonCommandAction.TableFormula),
        new("writer.table-header-row", WriterRibbonCommandAction.TableHeaderRow),
        new("writer.table-insert-above", WriterRibbonCommandAction.TableInsertAbove),
        new("writer.table-insert-below", WriterRibbonCommandAction.TableInsertBelow),
        new("writer.table-insert-col-left", WriterRibbonCommandAction.TableInsertColLeft),
        new("writer.table-insert-col-right", WriterRibbonCommandAction.TableInsertColRight),
        new("writer.table-merge-cells", WriterRibbonCommandAction.TableMergeCells),
        new("writer.table-split-cell", WriterRibbonCommandAction.TableSplitCell),
        new("writer.table-shading", WriterRibbonCommandAction.TableShading),
        new("writer.table-borders", WriterRibbonCommandAction.TableBorders),
        new("writer.table-last-column", WriterRibbonCommandAction.TableLastColumn),
        new("writer.table-last-row", WriterRibbonCommandAction.TableLastRow),
        new("writer.table-of-authorities", WriterRibbonCommandAction.TableOfAuthorities),
        new("writer.table-of-authorities-refresh", WriterRibbonCommandAction.TableOfAuthoritiesRefresh),
        new("writer.table-properties", WriterRibbonCommandAction.TableProperties),
        new("writer.table-repeat-header", WriterRibbonCommandAction.TableRepeatHeader),
        new("writer.table-row-height", WriterRibbonCommandAction.TableRowHeight),
        new("writer.table-select-cell", WriterRibbonCommandAction.TableSelectCell),
        new("writer.table-select-col", WriterRibbonCommandAction.TableSelectCol),
        new("writer.table-select-row", WriterRibbonCommandAction.TableSelectRow),
        new("writer.table-select-table", WriterRibbonCommandAction.TableSelectTable),
        new("writer.table-to-text", WriterRibbonCommandAction.TableToText),
        new("writer.table-view-gridlines", WriterRibbonCommandAction.TableViewGridlines),
        new("writer.tabs-dialog", WriterRibbonCommandAction.TabsDialog),
        new("writer.text-to-table", WriterRibbonCommandAction.TextToTable),
        new("writer.theme", WriterRibbonCommandAction.Theme),
        new("writer.theme-colors", WriterRibbonCommandAction.ThemeColors),
        new("writer.theme-effects", WriterRibbonCommandAction.ThemeEffects),
        new("writer.theme-fonts", WriterRibbonCommandAction.ThemeFonts),
        new("writer.thesaurus", WriterRibbonCommandAction.Thesaurus),
        new("writer.toc", WriterRibbonCommandAction.Toc),
        new("writer.toc-refresh", WriterRibbonCommandAction.TocRefresh),
        new("writer.tof", WriterRibbonCommandAction.Tof),
        new("writer.tof.equation", WriterRibbonCommandAction.Tof_Equation),
        new("writer.tof.figure", WriterRibbonCommandAction.Tof_Figure),
        new("writer.tof.table", WriterRibbonCommandAction.Tof_Table),
        new("writer.tof-refresh", WriterRibbonCommandAction.TofRefresh),
        new("writer.tof-refresh.equation", WriterRibbonCommandAction.TofRefresh_Equation),
        new("writer.tof-refresh.figure", WriterRibbonCommandAction.TofRefresh_Figure),
        new("writer.tof-refresh.table", WriterRibbonCommandAction.TofRefresh_Table),
        new("writer.toggle-field-codes", WriterRibbonCommandAction.ToggleFieldCodes),
        new("writer.underline", WriterRibbonCommandAction.Underline),
        new("writer.undo", WriterRibbonCommandAction.Undo),
        new("writer.update-fields", WriterRibbonCommandAction.UpdateFields),
        new("writer.watermark", WriterRibbonCommandAction.Watermark),
        new("writer.widow-control", WriterRibbonCommandAction.WidowControl),
        new("writer.wordart", WriterRibbonCommandAction.Wordart),
    ];

    private static readonly IReadOnlyDictionary<WriterRibbonCommandAction, WriterRibbonCommandRoute[]> RoutesByAction =
        RouteData
            .GroupBy(route => route.Action)
            .ToDictionary(group => group.Key, group => group.ToArray());

    public static IReadOnlyList<WriterRibbonCommandRoute> Routes => RouteData;

    public static WriterRibbonCommandBuildResult Build(WriterRibbonCommandBindingPorts bindings)
    {
        ArgumentNullException.ThrowIfNull(bindings);

        var registry = new RibbonCommandRegistry();
        var grouped = Enum.GetValues<WriterRibbonCommandGroup>()
            .ToDictionary(
                static group => group,
                static _ => new List<RibbonCommandId>());

        foreach (var route in RouteData)
        {
            if (!bindings.CanonicalBindings.TryGetValue(route.Action, out var command))
                continue;

            registry.Register(route.CommandId, command);
            grouped[WriterRibbonCommandGroupCatalog.Resolve(route.Action)].Add(route.CommandId);
        }

        foreach (var (commandId, command) in bindings.AdapterBindings)
            registry.Register(commandId, command);

        return new WriterRibbonCommandBuildResult(
            registry,
            grouped.ToDictionary(
                static pair => pair.Key,
                static pair => (IReadOnlyList<RibbonCommandId>)pair.Value.ToArray()),
            bindings.AdapterBindings.Keys.ToArray());
    }

    public static RibbonCommandId GetPrimaryCommandId(WriterRibbonCommandAction action)
    {
        if (!RoutesByAction.TryGetValue(action, out var routes) || routes.Length == 0)
            throw new ArgumentOutOfRangeException(nameof(action), action, "Unknown Writer ribbon action.");

        return routes[0].CommandId;
    }

    public static void Register(
        IRibbonCommandRegistry registry,
        WriterRibbonCommandAction action,
        IRibbonCommand nativeCommand)
    {
        ArgumentNullException.ThrowIfNull(registry);
        ArgumentNullException.ThrowIfNull(nativeCommand);

        if (!RoutesByAction.TryGetValue(action, out var routes))
            throw new ArgumentOutOfRangeException(nameof(action), action, "Unknown Writer ribbon action.");

        foreach (var route in routes)
            registry.Register(route.CommandId, nativeCommand);
    }

    public static IRibbonCommand RegisterAction(
        IRibbonCommandRegistry registry,
        WriterRibbonCommandAction action,
        Action execute,
        Func<bool>? isEnabled = null,
        Action? prepareExecution = null)
    {
        ArgumentNullException.ThrowIfNull(execute);
        var command = new DelegatedCommand(
            _ => execute(),
            isEnabled is null ? null : () => new RibbonCommandState(IsEnabled: isEnabled()),
            prepareExecution);
        Register(registry, action, command);
        return command;
    }

    public static IRibbonCommand RegisterValue(
        IRibbonCommandRegistry registry,
        WriterRibbonCommandAction action,
        Action<string?> execute,
        Func<bool>? isEnabled = null,
        Func<string?>? getValue = null,
        Action? prepareExecution = null)
    {
        ArgumentNullException.ThrowIfNull(execute);
        var command = new DelegatedCommand(
            context => execute(context.SelectedValue),
            isEnabled is null && getValue is null
                ? null
                : () => new RibbonCommandState(
                    IsEnabled: isEnabled?.Invoke() ?? true,
                    Value: getValue?.Invoke()),
            prepareExecution);
        Register(registry, action, command);
        return command;
    }

    public static IRibbonStatefulCommand RegisterToggle(
        IRibbonCommandRegistry registry,
        WriterRibbonCommandAction action,
        Action toggle,
        Func<bool> isChecked,
        Func<bool>? isEnabled = null,
        Action? prepareExecution = null)
    {
        ArgumentNullException.ThrowIfNull(toggle);
        ArgumentNullException.ThrowIfNull(isChecked);
        var command = new DelegatedCommand(
            _ => toggle(),
            () => new RibbonCommandState(
                IsEnabled: isEnabled?.Invoke() ?? true,
                IsChecked: isChecked()),
            prepareExecution);
        Register(registry, action, command);
        return command;
    }

    private sealed class DelegatedCommand(
        Action<RibbonCommandContext> execute,
        Func<RibbonCommandState>? getState,
        Action? prepareExecution) : IRibbonStatefulCommand
    {
        public void Execute(RibbonCommandContext context)
        {
            if (getState?.Invoke().IsEnabled == false)
                return;

            prepareExecution?.Invoke();
            execute(context);
        }

        public RibbonCommandState GetState() => getState?.Invoke() ?? RibbonCommandState.Default;
    }
}
